BUFFER_SIZE = 1024
ENCODING = "utf-8"
# Debe tener un retraso de 0.003s
DELAY_SECONDS = 0.000
# Deben ser 64 caracteres
STR_SIZE = 4
# Deben ser 1_000_000 de cadenas
NUM_STRS = 10
CODE_RECV_RM_STR_END = '2'
CODE_RECV_RM_STR = '3'
CODE_SEND_RESP_PROCESSED = '4'
CODE_SEND_RESP_PROCESSED_END = '5'
CODE_END = '6'